TRUTH = (
    "Apakah kamu memilih hidungmu?",
    "Apakah kamu bernyanyi di kamar mandi?",
    "Apakah kamu pernah berbicara sendiri di depan cermin?",
    "Apakah kamu pernah membuat hantu seseorang?",
    "Apakah kamu pernah berjalan di atas orang tuamu melakukan 'itu'?",
    "Siapa orang terakhir yang paling kamu sukai? Mengapa?",
    "Apakah kamu pernah diskors dari sekolah?",
    "Jika Anda harus memilih antara telanjang atau pikiran Anda muncul dalam gelembung pikiran di atas kepala Anda untuk dibaca semua orang, mana yang akan Anda pilih?",
    "Apa satu hal yang kamu takut kehilangan?",
    "Apakah kamu menyukai seseorang saat ini?",
    "Satu hal tentang sahabatmu yang membuatmu cemburu?",
    "Apakah kamu akan menipu pacarmu untuk pria kaya?",
    "Apa giliran terbesarmu?",
    "Kapan terakhir kali kamu berbohong kepada orang tuamu dan mengapa?",
    "Jelaskan pasangan ideal Anda.",
    "Apa hal paling menakutkan yang pernah kamu lakukan?",
    "Apakah kamu pernah mengupil dan memakannya?",
    "Kapan terakhir kali kamu berbohong kepada orang tuamu dan mengapa?",
    "Apakah Anda pernah berbohong tentang usia Anda untuk berpartisipasi dalam kontes?",
    "Apakah kamu pernah ketahuan sedang memeriksa seseorang?",
    "Apakah kamu berbicara dalam tidurmu?",
    "Apakah kamu pikir kamu akan menikahi pacarmu saat ini?",
    "Maukah Anda menukar saudara Anda dengan satu juta dolar?",
    "Maukah Anda Menampar Sahabat Anda Untuk Sejuta Dolar?",
    "Apakah kamu pernah naksir seorang guru?",
    "Apakah kamu pernah merokok?",
    "Apakah kamu pernah mencoba narkoba?",
    "Bagaimana dengan alkohol?",
    "Apakah kamu masih perawan?",
    "gambarkan pasangan sempurna Anda.",
    "Jika Anda dapat menghasilkan $ 1 juta, apakah Anda akan putus sekolah?",
    "Apa kebiasaan terburukmu?",
    "Berapa banyak orang yang kamu cium?",
    "Jelaskan seperti apa gebetanmu.",
    "Jika temanmu dan pacarmu sama-sama sekarat di depanmu, siapa yang akan mencoba menyelamatkan lebih dulu?",
    "Apakah menurutmu (Pacar/Pacar) temanmu itu keren?",
    "Jika seseorang bertanya kepada Anda seperti apa sahabat Anda, bagaimana Anda menggambarkannya?",
    "Apa pendapatmu tentang dia sekarang?",
    "Kya Apke Pasta Gigi Aku Namak Dia?",
    "Rasode Me Kon Tha?",
    "Jika Anda harus menukar teman Anda dengan selebriti impian Anda, teman mana yang akan Anda pilih?",
    "Maukah kamu berbagi sikat gigi dengan sahabatmu?",
    "Siapa yang lebih hot? Kamu atau temanmu?",
    "Siapa yang Bodoh?\n (A. Temanmu\n (B. Kamu",
    "Pernahkah Anda berbohong tentang sahabat Anda untuk membuat diri Anda terlihat lebih baik?",
    "Makanan apa yang tidak akan pernah kamu pesan di restoran?",
    "Apa satu hal yang tidak akan pernah kamu makan pada kencan pertama?",
    "Sudah berapa lama kamu tidak menyikat gigi?",
    "Sudah berapa lama kamu tidak mandi?",
)

DARE = (
    "Tampilkan foto paling memalukan di ponsel Anda",
    "Tampilkan lima orang terakhir yang Anda kirimi SMS dan apa isi pesannya",
    "Biarkan seluruh grup DM seseorang dari akun Instagram Anda",
    "Makan bawang putih mentah",
    "Lakukan 100 squat",
    "Simpan tiga es batu di mulutmu sampai meleleh",
    "Katakan sesuatu yang kotor kepada orang di sebelah kirimu. Kamu punya teman!",
    "Berikan pijatan kaki pada orang di sebelah kanan Anda",
    "Masukkan 10 cairan berbeda yang tersedia ke dalam cangkir dan minumlah",
    "* Ucapkan kata pertama yang muncul di pikiranmu",
    "Berikan lap dance kepada seseorang pilihan Anda",
    "Lepaskan empat potong pakaian",
    "Suka 15 posting pertama di umpan berita Facebook Anda",
    "Makan sesendok mustard",
    "Pejamkan matamu sampai kamu pergi lagi",
    "Kirim sext ke orang terakhir di buku telepon Anda",
    "Pamerkan wajah orgasme Anda",
    "Makan pisang dengan menggoda",
    "Kosongkan dompet / dompet Anda dan tunjukkan kepada semua orang apa yang ada di dalamnya",
    "Lakukan perayapan seksi terbaikmu",
    "Berpura-puralah menjadi orang di sebelah kananmu selama 10 menit",
    "Makan camilan tanpa menggunakan tangan",
    "Katakan dua hal jujur ​​tentang semua orang dalam grup",
    "Twerk sebentar",
    "Cobalah membuat grup tertawa secepat mungkin",
    "Cobalah untuk memasukkan seluruh kepalan tanganmu ke dalam mulutmu",
    "Ceritakan kepada semua orang kisah memalukan tentang dirimu",
    "Coba jilat sikumu",
    "Posting selfie tertua di ponsel Anda di Instagram Stories",
    "Ceritakan kisah paling menyedihkan yang kamu tahu",
    "Melolong seperti serigala selama dua menit",
    "Menari tanpa musik selama dua menit",
    "Tari tiang dengan tiang imajiner",
    "Biarkan orang lain menggelitikmu dan mencoba untuk tidak tertawa",
    "Masukkan makanan ringan ke dalam mulut Anda sekaligus sebanyak yang Anda bisa",
    "Kirim selfie terbaru Anda.",
    "Kirim selfie terjelekmu.",
    "Kirim tangkapan layar riwayat pencarian facebook Anda",
    "Kirim tangkapan layar galeri Anda.",
    "Kirim tangkapan layar kotak masuk messenger Anda",
    "Katakan sesuatu yang sangat intim.",
    "Kirim tangkapan layar kotak masuk twitter Anda",
    "Kirim tangkapan layar layar beranda Anda.",
    "Kirim cover lagu favoritmu. ",
    "Lakukan lelucon lirik pada seseorang dan kirimkan buktinya.",
    "Akui gebetanmu saat ini. ❤️",
    "Nyatakan siapa cinta sejatimu.",
    "Kirim tangkapan layar galeri Anda.",
    "Jadikan gambar gebetanmu sebagai dpmu.",
    "Sarankan saya lebih berani.",
)


# Diambil dari Openuserbot.
GDNIGHT = [
    "`Selamat malam, jaga mimpimu tetap hidup`",
    "`Malam, malam, untuk teman tersayang! Semoga tidurmu nyenyak!`",
    "`Semoga malam dipenuhi bintang untukmu. Semoga menghitung setiap orang, memberimu kepuasan!`",
    "`Semoga Anda mendapatkan kenyamanan, kebahagiaan, dan tidur nyenyak!`",
    "`Sekarang santai. Hari sudah berakhir. Kamu melakukan yang terbaik. Dan besok kamu akan melakukan yang lebih baik. Selamat Malam!`",
    "`Selamat malam untuk teman yang terbaik! Dapatkan empat puluh kedipanmu!`",
    "`Semoga bantalmu empuk, dan istirahatmu panjang! Selamat malam, kawan!`",
    "`Jangan ada masalah, sahabat! Selamat Malam!`",
    "`Beristirahatlah dengan nyenyak malam ini, teman!`",
    "`Selamat tidur, kawan! Tidur nyenyak!`",
    "`Selamat malam, teman! Kamu luar biasa!`",
    "`Relaksasi adalah untuk Anda! Selamat malam, teman!`",
    "`Selamat malam. Semoga mimpi indah malam ini.`",
    "`Tidur nyenyak, teman tersayang dan semoga mimpi indah.`",
    "`Saat kita menunggu hari yang baru, selamat malam dan semoga mimpi indah.`",
    "`Teman terkasih, semoga malammu damai dan bahagia. Selamat malam.`",
    "`Kegelapan tidak bisa bertahan selamanya. Jaga harapan tetap hidup. Selamat malam.`",
    "`Dengan cara apa pun kamu akan bermimpi indah malam ini. Selamat malam, sobat!`",
    "`Selamat malam, temanku. Saya berdoa agar Tuhan yang baik menjagamu saat kamu tidur. Mimpi indah.`",
    "`Selamat malam, sobat! Semoga Anda dipenuhi dengan ketenangan!`",
    "`Semoga malammu tenang, kawan! Semoga baik-baik saja!",
    "`Semoga Anda mendapatkan malam di mana Anda dapat mengisi ulang untuk besok!`",
    "`Tidurlah malam ini, teman baik, dan rasakan istirahat yang baik, besok!`",
    "`Semoga teman baik saya terbebas dari kerja keras seharian! Selamat Malam!`",
    "`Selamat malam, teman! Semoga Anda memiliki keheningan untuk tidur!`",
    "`Tidurlah malam ini, teman dan sehatlah! Ketahuilah bahwa Anda telah melakukan yang terbaik hari ini, dan bahwa Anda akan melakukan yang terbaik, besok!`",
    "`Teman, jangan ragu untuk menyelesaikan sesuatu! Ambil malam ini untuk bersantai dan melakukan lebih banyak, besok!`",
    "`Teman, saya ingin mengingatkan Anda bahwa pikiran Anda yang kuat telah membawa Anda kedamaian, sebelumnya. Semoga hal itu terjadi lagi, malam ini! Semoga Anda memegang pengakuan ini bersama Anda!`",
    "`Semoga Anda tenang, malam, teman! Berharap semuanya sesuai dengan keinginan Anda dan hari berikutnya memenuhi standar Anda!`",
    "`Semoga kegelapan malam menyelubungimu dalam tidur yang nyenyak dan nyenyak! Sahabat, semoga perasaan ini membawamu melewati hari berikutnya!`",
    "`Teman, semoga ketenangan yang Anda alami malam ini menggerakkan Anda untuk memiliki lebih banyak malam seperti itu! Semoga Anda menemukan kedamaian dan mempertahankannya!`",
    "`Semoga tidak ada kegiatan untukmu malam ini, kawan! Semoga sisa yang kamu miliki datang kepadamu dengan cepat! Semoga aktivitas yang kamu lakukan besok sesuai dengan kecepatanmu dan semua buatanmu sendiri!`",
    "`Ketika hari selesai, teman, semoga kamu tahu bahwa kamu telah melakukannya dengan baik! Ketika kamu tidur malam ini, teman, semoga kamu melihat semua yang kamu harapkan, besok!`",
    "`Ketika semuanya terhenti, teman, saya harap pikiran Anda baik-baik saja, saat Anda tertidur! Semoga pikiran itu tetap bersama Anda, sepanjang hari-hari Anda!`",
    "`Setiap hari, Anda mendorong saya untuk melakukan hal-hal baru, teman! Semoga istirahat malam ini membawa hari baru yang dipenuhi dengan keberanian dan acara menarik!`",
]

# Diambil dari Openuserbot.
GDMORNING = [
    "`Hidup ini penuh dengan ketidakpastian. Tapi akan selalu ada matahari terbit setelah setiap matahari terbenam. Selamat pagi!`",
    "`Tidak peduli seberapa buruk hari kemarin Anda. Hari ini, Anda akan membuatnya menjadi hari yang baik. Semoga Anda selamat pagi!`",
    "`Jika Anda ingin mendapatkan kesehatan dan kecantikan, Anda harus bangun pagi. Selamat pagi!`",
    "`Semoga pagi ini memberimu harapan baru untuk hidup! Semoga kamu bahagia dan menikmati setiap momennya. Selamat pagi!`",
    "`Semoga matahari menghujani Anda dengan berkah dan kemakmuran di hari-hari mendatang. Selamat pagi!`",
    "`Setiap matahari terbit menandai kebangkitan kehidupan atas kematian, harapan atas keputusasaan dan kebahagiaan atas penderitaan. Semoga pagi Anda sangat menyenangkan hari ini!`",
    "`Bangun dan jadikan diri Anda bagian dari pagi yang indah ini. Dunia yang indah menunggu di luar pintu Anda. Selamat bersenang-senang!`",
    "`Sambut pagi yang indah ini dengan senyum di wajah Anda. Saya harap Anda akan menjalani hari yang menyenangkan hari ini. Semoga pagi Anda sangat baik!`",
    "`Anda telah diberkati dengan satu hari lagi. Sungguh cara yang luar biasa untuk menyambut berkat dengan pagi yang begitu indah! Selamat pagi untuk Anda!`",
    "`Bangun di pagi yang begitu indah adalah jaminan untuk hari yang luar biasa. Saya harap Anda dapat memanfaatkannya dengan sebaik-baiknya. Selamat pagi!`",
    "`Tidak ada yang lebih menyegarkan daripada pagi yang indah yang menenangkan pikiran Anda dan memberi Anda alasan untuk tersenyum. Selamat pagi! Semoga hari Anda menyenangkan.`",
    "`Hari lain baru saja dimulai. Sambut berkah pagi yang indah ini. Bangkit dan bersinar seperti biasanya. Semoga pagimu indah!`",
    "`Bangun seperti matahari setiap pagi dan terangi dunia kehebatanmu. Banyak hal hebat yang ingin kamu capai hari ini. Selamat pagi!`",
    "`Hari baru telah datang dengan begitu banyak peluang baru untuk Anda. Raih semuanya dan manfaatkan hari Anda sebaik mungkin. Ini saya mengucapkan selamat pagi!`",
    "`Kegelapan malam telah berakhir. Matahari baru telah terbit untuk membimbingmu menuju kehidupan yang begitu cerah dan bahagia. Selamat pagi sayang!`",
    "`Bangun, minum secangkir teh pagi dan biarkan angin pagi menyegarkan Anda seperti pil kebahagiaan. Semoga Anda mendapatkan pagi yang baik dan hari yang baik di depan!`",
    "`Matahari terbit adalah yang terbaik; nikmati secangkir kopi atau teh bersama diri sendiri karena hari ini milikmu, selamat pagi! Semoga harimu menyenangkan.`",
    "`Hari yang buruk akan selalu memiliki pagi yang baik, semoga semua kekhawatiran Anda hilang dan semua yang Anda inginkan dapat menemukan tempat. Selamat pagi!`",
    "`Akhir yang hebat mungkin tidak ditentukan, tetapi awal kreatif yang baik dapat direncanakan dan dicapai. Selamat pagi, semoga harimu produktif!`",
    "`Memiliki pagi yang manis, secangkir kopi, hari ini bersama orang yang Anda cintai, adalah apa yang membuat pagi hari Anda menyenangkan!`",
    "`Apa pun bisa salah di hari itu tetapi pagi harus indah, jadi saya pastikan pagi Anda dimulai dengan indah. Good Morning!`",
    "`Buka matamu dengan senyuman, berdoa dan bersyukurlah bahwa kamu bangun untuk awal yang baru. Good Morning!`",
    "`Pagi bukan hanya matahari terbit tapi Keajaiban Tuhan Yang Indah yang mengalahkan kegelapan dan menebarkan cahaya. Good Morning.`",
    "`Hidup tidak pernah memberi Anda kesempatan kedua. Jadi, nikmati setiap bagiannya. Mengapa tidak memulai dengan pagi yang indah ini. Good Morning!`",
    "`Jika Anda ingin mendapatkan kesehatan dan kecantikan, Anda harus bangun pagi-pagi. Selamat pagi!`",
    "`Burung-burung menyanyikan melodi manis dan angin sepoi-sepoi bertiup melalui pepohonan, pagi yang sempurna untuk membangunkanmu. Selamat pagi!`",
    "`Pagi ini sangat santai dan indah sehingga aku benar-benar tidak ingin kamu melewatkannya. Jadi, bangunlah sahabatku. Selamat pagi untukmu!`",
    "`Pagi datang dengan kanvas kosong. Lukis sesukamu dan sebut hari ini. Bangun sekarang dan mulailah menciptakan hari yang sempurna. Selamat pagi!`",
    "`Setiap pagi membawa Anda harapan baru dan peluang baru. Jangan lewatkan salah satu dari mereka saat Anda sedang tidur. Selamat pagi!`",
    "`Mulailah hari Anda dengan tekad yang kuat dan sikap yang baik. Anda akan menjalani hari yang baik hari ini. Selamat pagi teman saya!`",
    "`Persahabatan adalah apa yang membuat hidup layak untuk dijalani. Saya ingin berterima kasih kepada Anda karena telah menjadi teman istimewa saya. Selamat pagi untuk Anda!`",
    "`Teman sepertimu cukup sulit didapat dalam hidup. Aku harus menganggap diriku cukup beruntung memilikimu. Selamat pagi. Semoga harimu menyenangkan!`",
    "`Semakin Anda menganggap diri Anda diberkati, Anda akan semakin diberkati. Terima kasih Tuhan untuk pagi yang indah ini dan biarkan persahabatan dan cinta menang pagi ini.`",
    "`Bangun dan cicipi secangkir persahabatan yang penuh cinta. Makanlah hatimu dari sepiring harapan. Untuk melengkapinya, garpu penuh kebaikan dan cinta. Cukup untuk selamat pagi yang bahagia!`",
    "`Sangat mudah membayangkan dunia akan kiamat. Tapi sulit membayangkan menghabiskan satu hari tanpa teman-temanku. Selamat pagi.`",
]

ABUSE_STRINGS = (
    "Owww ... Idiot bodoh seperti itu.",
    "Jangan minum dan mengetik.",
    "Saya pikir Anda harus pulang atau lebih baik ke rumah sakit jiwa.",
    "Perintah tidak ditemukan. Sama seperti otakmu.",
    "Apakah Anda sadar bahwa Anda mempermalukan diri sendiri? Ternyata tidak.",
    "Anda bisa mengetik lebih baik dari itu.",
    "Aturan bot 544 bagian 9 mencegah saya membalas manusia bodoh seperti Anda.",
    "Maaf, kami tidak menjual otak.",
    "Percayalah kamu tidak normal.",
    "Saya yakin otak Anda terasa seperti baru, mengingat Anda tidak pernah menggunakannya.",
    "Jika saya ingin bunuh diri, saya akan memanjat ego Anda dan melompat ke IQ Anda.",
    "Zombie memakan otak... kau aman.",
    "Kamu tidak berevolusi dari kera, mereka berevolusi dari kamu.",
    "Kembalilah dan bicara padaku ketika IQmu melebihi usiamu.",
    "Aku tidak mengatakan kamu bodoh, aku hanya mengatakan kamu bernasib buruk dalam hal berpikir.",
    "Bahasa apa yang kamu bicarakan? Karena kedengarannya seperti omong kosong.",
    "Kebodohan bukanlah kejahatan jadi kamu bebas untuk pergi.",
    "Anda adalah bukti bahwa evolusi BISA berjalan terbalik.",
    "Saya akan menanyakan berapa usia Anda, tetapi saya tahu Anda tidak dapat menghitung setinggi itu.",
    "Sebagai orang luar, apa pendapatmu tentang ras manusia?",
    "Otak bukanlah segalanya. Dalam kasusmu, mereka bukan apa-apa.",
    "Biasanya orang hidup dan belajar. Anda hanya hidup.",
    "Aku tidak tahu apa yang membuatmu begitu bodoh, tapi itu benar-benar berhasil.",
    "Teruslah bicara, suatu hari nanti kamu akan mengatakan sesuatu yang cerdas! (Aku ragu)",
    "Kejutkan aku, katakan sesuatu yang cerdas.",
    "IQ Anda lebih rendah dari ukuran sepatu Anda.",
    "Aduh! Neurotransmiter Anda tidak berfungsi lagi.",
    "Apakah kamu gila kamu bodoh.",
    "Setiap orang berhak menjadi bodoh tapi kamu menyalahgunakan hak istimewa.",
    "Maaf aku menyakiti perasaanmu saat aku menyebutmu bodoh. Aku pikir kamu sudah tahu itu.",
    "Anda harus mencoba mencicipi sianida.",
    "Enzim Anda dimaksudkan untuk mencerna racun tikus.",
    "Kamu harus mencoba tidur selamanya.",
    "Ambil pistol dan tembak dirimu sendiri.",
    "Anda bisa membuat rekor dunia dengan melompat dari pesawat tanpa parasut.",
    "Berhenti bicara BS dan lompat di depan kereta peluru yang sedang berjalan.",
    "Cobalah mandi dengan Asam Klorida daripada air.",
    "Coba ini: jika Anda menahan napas di bawah air selama satu jam, Anda bisa menahannya selamanya.",
    "Go Green! Berhenti menghirup Oksigen.",
    "Tuhan sedang mencarimu. Kamu harus pergi menemuinya.",
    "berikan 100% Anda. Sekarang, pergilah mendonorkan darah.",
    "Cobalah melompat dari gedung bertingkat seratus tetapi Anda hanya bisa melakukannya sekali.",
    "Kamu harus menyumbangkan otakmu karena kamu tidak pernah menggunakannya.",
    "Relawan untuk target dalam jarak tembak.",
    "Tembakan kepala itu menyenangkan. Ambil sendiri.",
    "Kamu harus mencoba berenang dengan hiu putih besar.",
    "Kamu harus mengecat dirimu dengan warna merah dan berlari dalam maraton banteng.",
    "Anda bisa tinggal di bawah air selama sisa hidup Anda tanpa kembali ke atas.",
    "Bagaimana kalau kamu berhenti bernapas selama 1 hari? Itu bagus.",
    "Cobalah memprovokasi harimau saat kalian berdua berada di dalam sangkar.",
    "Sudahkah Anda mencoba menembak diri sendiri setinggi 100m menggunakan kanon.",
    "Kamu harus mencoba memegang TNT di mulutmu dan menyalakannya.",
    "Cobalah bermain tangkap dan lempar dengan RDX itu menyenangkan.",
    "Saya mendengar phogine beracun tapi saya rasa Anda tidak keberatan menghirupnya untuk bersenang-senang.",
    "Luncurkan diri Anda ke luar angkasa sambil melupakan oksigen di Bumi.",
    "Kamu harus mencoba bermain ular tangga, dengan ular asli dan tanpa tangga.",
    "Menari telanjang di beberapa kabel HT.",
    "Gunung Berapi Aktif adalah kolam renang terbaik untuk Anda.",
    "Kamu harus mencoba mandi air panas di gunung berapi.",
    "Cobalah untuk menghabiskan satu hari di peti mati dan itu akan menjadi milikmu selamanya.",
    "Tembak Uranium dengan neutron yang bergerak lambat di hadapan Anda. Ini akan menjadi pengalaman yang berharga.",
    "Kamu bisa menjadi orang pertama yang menginjak matahari. Selamat mencoba.",
)

RUN_STRINGS = (
    "Kamu pikir kamu akan pergi kemana?",
    "Hah? apa? mereka kabur?",
    "ZZzzZZzz... Hah? apa? oh, hanya mereka lagi, tidak apa-apa.",
    "Kembali kesini!",
    "Tidak secepat itu...",
    "Awas tembok!",
    "Jangan tinggalkan aku sendiri dengan mereka!!",
    "Kamu lari, kamu mati.",
    "Lelucon tentangmu, aku ada di mana-mana",
    "Kau akan menyesalinya...",
    "Kamu juga bisa mencoba /kickme, kudengar itu menyenangkan.",
    "Pergi ganggu orang lain, tidak ada yang peduli di sini.",
    "Kamu bisa lari, tapi kamu tidak bisa bersembunyi.",
    "Hanya itu yang kamu punya?",
    "Saya di belakang Anda...",
    "Kamu punya teman!",
    "Kita bisa melakukan ini dengan cara yang mudah, atau dengan cara yang sulit.",
    "Kau hanya tidak mengerti, kan?",
    "Ya, lebih baik kamu lari!",
    "Tolong, ingatkan aku betapa aku peduli?",
    "Aku akan berlari lebih cepat jika aku jadi kamu.",
    "Itu pasti droid yang kita cari.",
    "Semoga peluang selalu menguntungkan Anda.",
    "Kata-kata terakhir yang terkenal.",
    "Dan mereka menghilang selamanya, tidak pernah terlihat lagi.",
    '"Oh, lihat aku! Aku sangat keren, aku bisa lari dari bot!" - orang ini',
    "Yeah yeah, tap saja /kickme sudah.",
    "Ini, ambil cincin ini dan pergilah ke Mordor selagi kamu melakukannya.",
    "Legenda mengatakan, mereka masih berjalan ...",
    "Tidak seperti Harry Potter, orang tuamu tidak bisa melindungimu dariku.",
    "Ketakutan mengarah pada kemarahan. Kemarahan mengarah pada kebencian. Kebencian menyebabkan penderitaan. Jika Anda terus berlari dalam ketakutan, Anda mungkin"
    "jadilah Vader berikutnya.",
    "Beberapa perhitungan kemudian, saya telah memutuskan minat saya pada kejahatan Anda persis 0.",
    "Legenda mengatakan, mereka masih berjalan.",
    "Pertahankan, toh kami tidak yakin kami menginginkanmu di sini.",
    "Kamu seorang wiza- Oh. Tunggu. Kamu bukan Harry, teruslah bergerak.",
    "TIDAK BERLARI DI LOrong!",
    "Hasta la vista, sayang.",
    "Siapa yang membiarkan anjing keluar?",
    "Lucu, karena tidak ada yang peduli.",
    "Ah, sayang sekali. Aku suka yang itu.",
    "Terus terang, sayangku, aku tidak peduli.",
    "Milkshake saya membawa semua anak laki-laki ke halaman ... Jadi lari lebih cepat!",
    "Kamu tidak bisa MENANGANI kebenaran!",
    "Dulu, di galaksi yang sangat jauh ... Seseorang akan peduli tentang itu. Tapi sekarang tidak lagi.",
    "Hei, lihat mereka! Mereka lari dari banhammer yang tak terhindarkan... Lucu.",
    "Han menembak dulu. Aku juga.",
    "Apa yang kamu kejar, kelinci putih?",
    "Seperti yang akan dikatakan Dokter... LARI!",
)


PAT_TEMPLATES = (
    "Patt Se Headshot!",
    "{user1} menepuk {user2} di kepala.",
    "*usap kepala {user2} dengan lembut*.",
    "*{user1} mofumofus {user2}'s head*",
    "*{user1} mengacaukan kepala {user2}*",
    "*{user1} menggosok kepala {user2} dengan intens*",
    "Waifu*{user2} menepuk-nepuk kepalanya*",
    "*{user2} mendapat headpats gratis*",
    "Tidak ada tepukan untuk {user2}!",
    "Oh tidak! Kita semua kehabisan tepukan.",
    "Ini adalah zona larangan tepuk yang ditunjuk!",
    "{user1} memanjakan {user2} dengan headpats!",
    "{user2} menerima satu headpat gratis!",
    "{user1} menepuk kepala {user2} sambil memberikan bantal pangkuan",
    "{user1} dengan agresif menepuk {user2}",
    "{user1} dengan lembut membelai kepala {user2}",
    "tepuk, tepuk, tepuk, tepuk",
    "{user2} tidak bisa lepas dari tepukan kepala {user1}",
    "{user1} menggosok {user2} di leher",
    "Harus... memeras... KEPALA",
    "{user1} menepuk kepala {user2} dengan tepukan",
    "{user1} menepuk {user2} secara tidak terduga",
    "{user1} menepuk {user2} dengan persetujuan, mungkin?",
    "Pat tepuk, {user2} honto kawaii ne!",
    "{user1} menepuk kepala {user2} pada pukul 420",
    "{user1} gosok perut {user2}",
    "{user1} tepuk {user2} dengan ramah",
    "{user2} menggunakan HEADPATS? O KAWAII KOTO",
    "(*´ω´(*｀ω｀)",
    "(ｏ・_・)ノ”(ᴗ_ )",
    "(*￣▽￣)ノ”(- -*)",
    "(っ´ω`)ﾉ(╥ω╥)",
    "( )ﾉ(´･ω･`) ",
)

PAT_GIFS = (
    "CgACAgQAAxkBAAIByV--JhjY9HrIzpRnYY3KKvAgfc5CAAJHAgACOvCNUjkBPKk8gG_QHgQ",
    "CgACAgQAAxkBAAIByF--JhiD_dRrZDN-aYMpi-s_-omHAAJcAgACDY6EUjMkLsa2rXTXHgQ",
    "CgACAgQAAx0CSxgUbQACJf9f4W4bq_BWoHgMjTzSLBIx0RO0awACygYAAiYNiFPz3-km0vNPWR4E",
    "CgACAgQAAx0CSxgUbQACJfpf4W4IIBVwRXeSvSTcunixHFzmtQACagIAAv0FLVNvZ_FCfNrvsR4E",
    "CgACAgQAAxkBAAIBx1--JhhEaEdSqi4mQiwzyN1egkZ8AAIjAgACNyiMUozDfqiw_yObHgQ",
    "CgACAgQAAxkBAAIBxl--JhimxY9FVs2LYRhNYE41V2fGAAIUAgACTF2MUtgrqDLvmUVeHgQ",
    "CgACAgQAAxkBAAIB0l--JqKztJB24eqJLe8mfPPPYVDhAAIVAgACeVbVUnaV3UIO1KK-HgQ",
)

PAT_STIKER = (
    "CAACAgQAAxkBAAICYl--eHbgPobSdk9Tj4nSxleQ0TdJAAKvAAPVMzML3OVCdzeQd1seBA",
    "CAACAgQAAxkBAAICY1--eHfZk1pwGb_EJb6Dj3ep8LJfAAKtAAPVMzMLgmD0afnZcfIeBA",
    "CAACAgQAAxkBAAICZF--eHlF0n4mZo2M3CaYu2OU013VAAK1AAPVMzMLs-0qSivU6JweBA",
    "CAACAgQAAxkBAAICZl--eH28owxPadJ0HOfmVTiltdCYAAK7AAPVMzML2w_RrJI2ClweBA",
    "CAACAgQAAxkBAAICZ1--eH3JMYs3KFC_eVjdtQfClgUfAAK9AAPVMzML0XUtOSPmUKIeBA",
    "CAACAgQAAxkBAAICaF--eH4dBpnjndfqXPCGhTngt-OIAAK_AAPVMzMLHdlAuFtjtSUeBA",
    "CAACAgQAAxkBAAICaV--eH-zmpo-ykUzRDJ-jWraxfQmAALDAAPVMzMLHlxOVFgekGEeBA",
    "CAACAgQAAxkBAAICal--eIEpEdc9Gk5OqzZVsVnOGGaRAALFAAPVMzMLX8y0ifckrQ8eBA",
    "CAACAgQAAxkBAAICa1--eIHWTj20mbxn0wc4qfZBqWiXAALHAAPVMzMLz_FARSAVUQUEBA",
    "CAACAgQAAxkBAAICbF--eJDiZYA6aRndG9upuR2_XfIgAAMBAALVMzML55oysf4qBxgeBA",
    "CAACAgQAAxkBAAICbV--eJLtLbJrqeKgG5lllQ2gqlCcAAL6AAPVMzMLKhav7ii41zQeBA",
    "CAACAgQAAxkBAAICbl--eJVJO_moWtoktLrg3jzUaeTkAAJ_AQAC1TMzCy8SeosY4uaXHgQ",
    "CAACAgQAAxkBAAICb1--eJVMMK6yxFEWF92K5jr4eG0EAAKCAQAC1TMzC87tPZLqbwkSHgQ",
    "CAACAgQAAxkBAAICcF--eJbOrVL_MkJo5kw_zfIS4TEzAAI6AQAC1TMzC3h8vVt-_pjtHgQ",
    "CAACAgQAAxkBAAICcV--eJb1nknGXwKgGE5aXDcawgK3AAJ6AQAC1TMzCweeI_mdwBUIHgQ",
    "CAACAgQAAxkBAAICcl--eJk_0PxzYNwy1TZ5IWwsW__sAAKyAQAC1TMzC-yfrpJDR9k7HgQ",
)

SLAP_TEMPLATES = (
    "{user2} ditembak oleh {user1}.",
    "{user2} masuk ke kaktus saat mencoba melarikan diri {user1}.",
    "{user2} tenggelam saat mencoba melarikan diri {user1}.",
    "{user2} jatuh ke dalam sepetak kaktus.",
    "{user2} terbakar.",
    "{user2} terbakar sampai mati.",
    "{user2} terbakar habis saat bertarung dengan {user1}.",
    "{user2} tersambar petir.",
    "{user2} dibunuh oleh {user1}.",
    "{user2} dibunuh oleh sihir.",
    "{user2} mati kelaparan.",
    "{user2} jatuh dari dunia.",
    "{user2} dihancurkan oleh {user1}.",
    "Tulang {user2} tergores bersih oleh angin yang sunyi.",
    "{user2} pingsan.",
    "{user2} Pokemon yang bisa digunakan habis! {user2} kehabisan!.",
    "{user2} Pokemon yang bisa digunakan habis! {user2} pingsan!.",
    "{user2} mengucapkan selamat tinggal pada dunia yang kejam ini.",
    "{user2} mendapat rekt.",
    "{user2} digergaji menjadi dua oleh {user1}.",
    "Melon {user2} dibagi oleh {user1}.",
    "{user2} diiris dan dipotong dadu oleh {user1}.",
    "Kematian {user2} membuat takik lagi di kapak {user1}.",
    "{user2} meninggal karena penyakit tropis misterius {user1}.",
    "{user2} bermain kentang panas dengan granat.",
    "{user2} ditikam oleh {user1}.",
    "{user2} memakan granat.",
    "{user2} untuk makan malam!",
    "{user2} dihentikan oleh {user1}.",
    "{user2} ditembak sebelum dilempar keluar dari pesawat.",
    "{user2} mengalami kesalahan.",
    "{user2} mati dan bereinkarnasi sebagai kambing.",
    "{user1} melemparkan {user2} dari gedung.",
    "{user2} mendapat penguburan prematur.",
    "{user1} mengirim spam ke email {user2}.",
    "{user1} pukul {user2} dengan pesawat ruang angkasa kecil antarbintang.",
    "{user1} masukkan {user2} di check-mate.",
    "{user1} RSA-encrypted {user2} dan menghapus kunci pribadi.",
    "{user1} taruh {user2} di zona teman.",
    "{user1} menampar {user2} dengan permintaan penghapusan DMCA!",
    "{user2} meninggal karena gangren rumah sakit.",
    "{user2} mendapat telepon dari Dokter {user1}.",
    "{user1} memenggal {user2}.",
    "{user2} dilempari batu...oleh massa yang marah.",
    "{user1} menggugat celana {user2}.",
    "{user2} satu pukulan KO oleh {user1}.",
    "{user1} mengirim {user2} ke lubang memori.",
    "{user2} adalah kesalahan. - '{user1}' ",
    "{user1} memeriksa {user2} dalam dua gerakan.",
    "{user2} dibuat berlebihan.",
    "{user1} {hits} {user2} dengan kelelawar!.",
    "{user1} {memukul} {user2} dengan Tendangan Taijutsu!.",
    "{user1} {hits} {user2} dengan X-Gloves!.",
    "{user1} {hits} {user2} dengan Pukulan Jet!.",
    "{user1} {hits} {user2} dengan Jet Pistol!.",
    "{user1} {hits} {user2} dengan Smash Amerika Serikat!.",
    "{user1} {hits} {user2} dengan Detroit Smash!.",
    "{user1} {hits} {user2} dengan Texas Smash!.",
    "{user1} {hits} {user2} dengan California Smash!.",
    "{user1} {hits} {user2} dengan New Hampshire Smash!.",
    "{user1} {hits} {user2} dengan Missouri Smash!.",
    "{user1} {hits} {user2} dengan Carolina Smash!.",
    "{user1} {hits} {user2} dengan King Kong Gun!.",
    "{user1} {hits} {user2} dengan tongkat baseball - yang terbuat dari logam.!.",
    "* Pukulan serius {user2}*.",
    "* Pukulan normal {user2}*.",
    "* Pukulan Normal Berturut-turut {user2}*.",
    "* Pukulan Normal Dua Tangan Berturut-turut {user2}*.",
    "* Mengabaikan {user2} untuk membiarkan mereka mati karena malu*.",
    "*menunjuk {user2}* Ada apa dengan lancang... anak hilang ini?.",
    "* Memukul {user2} dengan Tornado Api*.",
    "{user1} menusuk mata {user2} !",
    "{user1} menyodok {user2} di samping!",
    "{user1} mencolek {user2}!",
    "{user1} menusuk {user2} dengan jarum!",
    "{user1} mencolek {user2} dengan pena!",
    "{user1} menusuk {user2} dengan pistol setrum!",
    "{user2} diam-diam adalah Furry!.",
    "Hei Semuanya! {user1} memintaku untuk menjadi jahat!",
    "( _･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Ambil ini {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Di sini {user2} pegang ini\n(｀・ω・)つ ●~＊",
    "( _・)ノΞ●~* {user2},Shinaeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Semburan serangga {user2}*.",
    "( )ﾉ占~<巛巛巛.\n-{user2} Kamu mengganggu!",
    "( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} dengan {item}.",
    "{user1} {hits} {user2} berhadapan dengan {item}.",
    "{user1} {hits} {user2} sedikit dengan {item}.",
    "{user1} {melempar} {item} ke {user2}.",
    "{user1} mengambil {item} dan {melempar} ke wajah {user2}.",
    "{user1} meluncurkan {item} ke arah umum {user2}.",
    "{user1} mulai menampar {user2} konyol dengan {item}.",
    "{user1} menyematkan {user2} ke bawah dan berulang kali {memukul} mereka dengan {item}.",
    "{user1} mengambil {item} dan {hits} {user2} dengannya.",
    "{user1} mengikat {user2} ke kursi dan {melempar} {item} ke mereka.",
    "{user1} memberikan dorongan ramah untuk membantu {user2} belajar berenang di lava.",
    "{user1} menindas {user2}.",
    "Nyaan memakan kaki {user2}. *nomnomnom*",
    "{user1} {melempar} bola master ke {user2}, perlawanan sia-sia.",
    "{user1} mengenai {user2} dengan sinar aksi...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara {user2}.",
    "{user1} ora ora {user2}.",
    "{user1} muda muda's {user2}.",
    "{user2} diubah menjadi referensi Jojo!",
    "{user1} klik {user2} dengan {item}.",
    "Ronde 2!..Siap?.. FIGHT!!",
)

ITEMS = (
    "wajan besi cor",
    "meong marah",
    "kelelawar kriket",
    "tongkat kayu",
    "sekop",
    "pemanggang roti",
    "Book",
    "laptop",
    "ayam karet",
    "kelelawar berduri",
    "batu berat",
    "sebongkah kotoran",
    "ton batu bata",
    "rasengan",
    "bom roh",
    "Bodhisattva Guanyin Tipe 100",
    "rasenshuriken",
    "Murasame",
    "melarang",
    "chunchunmaru",
    "Kubikiribōch",
    "rasengan",
    "kucing terbang bulat",
)

THROW = (
    "melempar",
    "teman kencan",
    "cekik",
    "melempar",
)

HIT = (
    "pukulan",
    "memukul",
    "menampar",
    "memukul",
    "memukul",
    "tepuk",
)

PUNCH_TEMPLATES = (
    "{user1} {meninju} {user2} dengan {item}.",
    "{user1} {meninju} {user2} di wajah dengan {item}.",
    "{user1} {meninju} {user2} sedikit dengan {item}.",
    "{user1} {meninju} {user2} di wajah mereka. 👊",
)

HUG_TEMPLATES = (
    "{pengguna1} {peluk} {pengguna2}.",
    "{user1} {peluk} {user2} dengan hangat.",
    "{user1} {peluk} {user2} dengan cinta. 💘",
    "{user1} {peluk} {user2} dengan kebaikan.",
)

PUNCH = (
    "meninju",
    "tertekan",
    "memukul",
)

HUG = ("memeluk", "memeluk", "mencium", "mencubit")

# Kredit string tabel: @DaisyX

TABLE = (
    "(╯°□°）╯彡 ┻━┻",
    "Saya kehabisan meja, akan memesan lebih banyak.",
    "Lakukan beberapa pekerjaan alih-alih meja flippin.",
)

GBUN = (
    "Hati-hati! Bot-Admeme Ini Dapat Menghancurkan Anda Langsung Dari Peta.",
    "Kurasa Kamu Lupa Ejaan GBAN Mungkin...?",
    "Jangan Menyalahgunakan Kekuatanmu...",
    "Nah, Dia Terlihat Tidak Bersalah...",
)


GBAM = "<b>Awal Bam Global Untuk {user2}</b> \n \nId Obrolan : <code>{chatid}</code> \nAlasan : <i>{reason}</i> \nGBditimbun Oleh {pengguna1}"


GBAM_REASON = (
    "sasta noob",
    "pencuri sasta waifu",
    "sasta white-het hekur",
    "sasta white-het codur",
    "sasta white-het vala chintu",
    "sasta heksa hekur",
    "sasta hexa playur",
    "sasta tiktokuro",
    "Sasta anggota tim 7",
    "sasta selmon boi",
    "pemain sasta fri-api",
    "sasta chota bhim",
    "sasta chapri",
    "sasta jony dosa",
    "sasta chhapri nibba",
    "sasta niba",
    "sasti ria chokroborti",
    "sasti nibbi",
    "sasta kemping",
)


GIFS = [
    "CgACAgQAAx0ESlgI7AACAqxfu09m1qXPJjRiyRMyJxswdUA5LwACaAgAAlZD0VEtI5O_RO_rSB4E",
    "CgACAgUAAx0CSlgI7AACA2Ffu4L_5S3dL5YUWNGBEBL60oBNIgACqwADg_8wVe6pdZO2-TIxHgQ",
    "CgACAgQAAx0ESlgI7AACA3Nfu4M3oUQUhZ6X-I5LNrQkWJ1iogACaAgAAlZD0VGB9mP1VKDQJR4E",
]


MEMUTUSKAN = ("Ya.", "Tidak.", "Mungkin.", "Tidak.")


# Kredit string AFK: PaperPlaneExtended!
AFKRPL = (
    "<b>{}</b> sedang sibuk sekarang. Silakan bicara di dalam tas dan ketika mereka kembali, Anda bisa memberinya tas!",
    "<b>{}</b> sedang pergi sekarang. Jika Anda butuh sesuatu, tinggalkan pesan setelah bunyi bip:\n<code>beeeeeeeeeeeeeeeeeeeeeeeeeep</code>!",
    "Anda baru saja melewatkan <b>{}</b>, lain kali bidik lebih baik.",
    "{} akan kembali dalam beberapa menit dan jika tidak...,\ntunggu lebih lama.",
    "Mawar berwarna merah,\nUngu berwarna biru,\nTinggalkan pesan,\nDan {} akan menghubungi Anda.",
    "Jika Anda belum mengetahuinya,\n{} tidak ada di sini.",
    "{} pergi ke arah sana\n---->",
    "{} pergi ke sini\n<----",
    "{} tidak ada di sini jadi berhentilah menulis kepada mereka,\atau Anda tidak akan menemukan diri Anda dengan layar penuh dengan pesan Anda sendiri.",
    "Hidup ini begitu singkat, ada begitu banyak hal yang harus dilakukan...\n{} adalah salah satunya..",
    "{} sedang jauh dari keyboard saat ini, tetapi jika Anda berteriak cukup keras di layar, mereka mungkin hanya mendengar Anda.",
)

NOAFK = (
    "{} di sini!",
    "{} kembali!",
    "{} sekarang dalam obrolan!",
    "{} sudah bangun!",
    "{} kembali online!",
    "{} akhirnya di sini!",
    "Selamat datang kembali! {}",
    "OwO {} ada di sini!",
)

AFK = (
    "Cya {}!",
    "Sampai jumpa {}.",
    "Sampai jumpa lagi {}!",
    "Selamat tinggal {}!",
    "Segera kembali {}!",
    "Kthnxbye {}..",
)

SHGS = (
    "┐(´д｀)┌",
    "┐(´～｀)┌",
    "┐(´ー｀)┌",
    "┐(￣ヘ￣)┌",
    "╮(╯∀╰)╭",
    "╮(╯_╰)╭",
    "┐(´д`)┌",
    "┐(´∀｀)┌",
    "ʅ(́◡◝)ʃ",
    "┐(ﾟ～ﾟ)┌",
    "┐('д')┌",
    "┐('～`;)┌",
    "ヘ(´－｀;)ヘ",
    "┐( -“-)┌",
    "ʅ（´◔౪◔）ʃ",
    "ヽ(゜～゜o)ノ",
    "ヽ(~～~ )ノ",
    "┐(~ー~;)┌",
    "┐(-。ー;)┌",
    r"¯\_(ツ)_/¯",
    r"¯\_(⊙_ʖ⊙)_/¯",
    r"¯\_༼ _/¯",
    "乁( ) ",
)

CRI = (
    "أ‿أ",
    "╥﹏╥",
    "(;﹏;)",
    "(ToT)",
    "(┳Д┳)",
    "(ಥ﹏ಥ)",
    "（；へ：）",
    "(T＿T)",
    "（πーπ）",
    "(Ｔ▽Ｔ)",
    "(⋟﹏⋞)",
    "（ｉДｉ）",
    "(´Д⊂ヽ",
    "(;Д;)",
    "（>﹏<）",
    "(TдT)",
    "(つ﹏⊂)",
    "༼☯﹏☯༽",
    "(ノ﹏ヽ)",
    "(ノAヽ)",
    "(╥_╥)",
    "(T⌓T)",
    "(༎ຶ⌑༎ຶ)",
    "(☍﹏⁰)｡",
    "(ಥ_ʖಥ)",
    "(つд⊂)",
    "(≖͞_≖̥)",
    "(இ﹏இ`｡)",
    "༼ಢ_ಢ༽",
    "༼ ",
)


BEING_LOGICAL = (
    "Gelembung bawah air dan tetesan hujan benar-benar berlawanan satu sama lain.",
    "Jika Anda membeli penghapus, Anda benar-benar membayar kesalahan Anda.",
    "manusia menjajah bulan, itu mungkin akan menarik rumah jompo karena gravitasi yang lebih lemah akan membuat orang tua merasa lebih kuat.",
    "Orang yang paling Anda sayangi memiliki potensi paling besar untuk menghancurkan Anda.",
    "Any video with “wait for it” in the title is simply too long.",
    "Usia Anda dalam tahun adalah berapa kali Anda mengelilingi Matahari, tetapi usia Anda dalam bulan adalah berapa kali Bulan mengelilingi Anda.",
    "Menggigit lidah saat makan adalah contoh sempurna bagaimana Anda masih bisa mengacau, bahkan dengan pengalaman puluhan tahun.",
    "Mengatakan bahwa rumah Anda ditenagai oleh reaktor fusi Nuklir nirkabel yang berjarak 93 Juta mil jauhnya terdengar jauh lebih keren daripada hanya mengatakan Anda memiliki panel surya di atap Anda.",
    "Perasaan yang paling menghancurkan adalah ketika seseorang tersenyum padamu di jalan dan kamu tidak bereaksi cukup cepat untuk membalas senyumanmu.",
    "Gigi terus-menerus membutuhkan perawatan untuk mencegah pembusukan mereka saat hidup, namun mereka berhasil bertahan selama ribuan tahun terkubur sebagai fosil.",
    "Folder adalah untuk hal-hal yang tidak ingin Anda lipat.",
    "Bangun di pagi hari terkadang terasa seperti melanjutkan film buruk yang Anda putuskan untuk berhenti menonton.",
    "Jika semuanya berjalan lancar, Anda mungkin tidak akan ingat hari ini.",
    "Ketika Anda bertemu orang baru dalam kehidupan nyata, Anda membuka lebih banyak karakter untuk dunia impian Anda.",
    "Mungkin jika mereka mengganti nama tabir surya menjadi “anti-cancer cream” lebih banyak orang akan memakainya.",
    "200 tahun yang lalu, orang tidak akan pernah menduga bahwa manusia di masa depan akan berkomunikasi dengan mengetuk kaca secara diam-diam.",
    "Orang tua khawatir tentang apa yang diunduh putra mereka dan khawatir tentang apa yang diunggah putri mereka.",
    "Sungguh gila bagaimana Anda bisa seusia dengan seseorang, tetapi pada tahap yang sama sekali berbeda dalam hidup Anda.",
    "Ketika Anda berpikir Anda ingin mati, Anda benar-benar tidak ingin mati, Anda hanya tidak ingin hidup seperti ini.",
    "Secara teknis, tidak ada seorang pun yang pernah berada di ruangan kosong.",
    "Bawang adalah makanan utama. Anda mungkin tidak akan menikmatinya sendirian, tetapi Anda akan melewatkannya jika tidak ada di sana.",
    "Kami berlari ke mana-mana di videogame karena kami terlalu malas untuk berjalan, tetapi dalam kehidupan nyata kami berjalan di mana-mana karena kami terlalu malas untuk berlari.",
    "Setiap keputusan yang pernah Anda buat telah membawa Anda untuk membaca kalimat ini.",
    "Kata 'tenang' sering diucapkan sangat keras.",
    "Semua orang ingin Anda bekerja keras, tetapi tidak ada yang ingin mendengar tentang seberapa keras Anda bekerja.",
    "Kami menyikat gigi dengan rambut di atas tongkat dan menyikat rambut dengan gigi di atas tongkat.",
    "Tidak ada yang mengingat momen canggungmu tapi mereka terlalu sibuk mengingat momen mereka sendiri.",
    "Orang bodoh mencoba mengatakan ide sederhana serumit mungkin sedangkan orang pintar mencoba mengatakan ide kompleks sesederhana mungkin.",
    "Beberapa orang berpikir mereka lebih baik darimu karena mereka tumbuh lebih kaya. Beberapa orang berpikir mereka lebih baik darimu karena mereka tumbuh lebih miskin.",
    "Ironi terbesar adalah bahwa komputer & ponsel diciptakan untuk menghemat waktu!",
    "Setelah madu pertama kali ditemukan, kemungkinan ada periode di mana orang menguji rasa lendir yang tersedia dari serangga.",
    "Kamu tahu kamu semakin tua ketika orang tuamu mulai mengecewakanmu, bukannya kamu mengecewakan mereka.",
    "Manusia dirancang untuk belajar melalui pengalaman namun sistem pendidikan telah membuatnya sehingga kita tidak mendapatkan pengalaman.",
    "Dengan berfokus pada berkedip, Anda berkedip lebih lambat ... Sama untuk bernapas.",
    "Pengemudi yang terburu-buru menerobos lalu lintas biasanya menyebabkan kecelakaan yang membuat lalu lintas yang mereka coba hindari.",
    "Karakter yang menikah dalam fiksi benar-benar dibuat untuk satu sama lain.",
    "Bayi adalah hard drive bersih yang dapat diprogram dengan bahasa apa pun.",
    "Mungkin ada obat ajaib yang menyembuhkan setiap penyakit manusia, yang tidak akan pernah kita ketahui karena tidak bekerja pada tikus.",
    "Badak berevolusi untuk menumbuhkan tanduk untuk perlindungan, tetapi itulah yang membuat mereka punah.",
    "Mungkin kita tidak menemukan penjelajah waktu karena kita semua mati dalam 25-50 tahun.",
    "Tidur adalah versi percobaan kematian, bahkan dilengkapi dengan iklan berdasarkan aktivitas Anda.",
    "Hal yang paling tidak realistis tentang film Spy adalah seberapa bersih sistem ventilasi udaranya!",
    "Dalam game, kami bermain melalui mode mudah untuk membuka mode keras. Dalam hidup, kami bermain melalui mode sulit untuk membuka mode mudah.",
    "Orang yang diam tampak lebih pintar daripada orang yang berisik, karena mereka menyimpan pikiran bodoh mereka untuk diri mereka sendiri.",
    "Jika Greenland benar-benar berubah menjadi hijau, kita semua kacau.",
    "Jika seseorang mengatakan hal-hal pintar dalam mimpimu, itu sebenarnya menunjukkan kepintaranmu sendiri.",
    "Kutipan film terkenal dikreditkan ke aktor dan bukan penulis sebenarnya yang menulisnya.",
    "Tidak ada yang benar-benar mengajari Anda cara mengendarai sepeda. Mereka hanya membuat Anda bersemangat sampai Anda berhasil.",
    "Tanyakan pada diri sendiri mengapa otak mengabaikan detik.",
    "Anda mungkin lupa sekitar 80% dari seluruh hidup Anda dan sebagian besar kenangan yang Anda ingat tidak terlalu akurat dengan apa yang sebenarnya terjadi.",
    "Akan jauh lebih sulit bagi anak-anak untuk menang melawan orang tua mereka di video game di masa depan.",
    "Setiap orang memiliki kekurangan, jika kamu tidak mengenali kekuranganmu, kamu memiliki yang baru.",
    "Membesarkan anak adalah melatih penggantimu.",
    "'O'pen dimulai dengan lingkaran Tertutup, dan 'Tutup dimulai dengan lingkaran terbuka.",
    "Selalu ada seseorang yang membencimu tanpa alasan, dan masih melakukannya.",
    "Setelah popcorn ditemukan, pasti ada banyak biji acak yang dipanggang untuk melihat apakah efeknya sama.",
    "Semakin penting tidur yang nyenyak, semakin sulit untuk tertidur.",
    "Berbahagialah mereka yang dapat dengan tepat menggambarkan jenis potongan rambut yang mereka inginkan kepada penata rambut baru.",
    "Terlalu banyak orang menghabiskan uang yang tidak mereka peroleh, untuk membeli barang yang tidak mereka inginkan, untuk mengesankan orang yang tidak mereka sukai!",
    "Pegawai taman hiburan harus pandai membedakan antara teriakan horor dan kegembiraan.",
    "6 hingga 6:30 terasa lebih setengah jam daripada 5:50 hingga 6:20",
    "Mendapatkan kata sandi Anda dengan benar pada upaya masuk terakhir sebelum penguncian adalah hal yang paling dekat dengan melucuti bom pada menit terakhir yang akan dialami sebagian besar dari kita.",
    "Mendengarkan podcast sebelum tidur adalah waktu cerita versi dewasa.",
    "Jika semua penjahat berhenti merampok maka industri keamanan akan jatuh di mana mereka dapat dengan mudah kembali merampok.",
    "Satu ton paus benar-benar hanya seperti setengah paus.",
    "Ketika Anda menjadi tua, Anda yang lama secara teknis adalah Anda yang baru, dan diri Anda yang muda adalah Anda yang lama.",
    "Anda mungkin tidak akan menemukan banyak ulasan negatif tentang parasut di Internet.",
    "Kami menunjukkan cinta dan kekaguman paling besar kepada orang-orang ketika mereka tidak lagi ada untuk menghargainya.",
    "Kami telah berlatih tidur ribuan kali, namun tidak dapat melakukannya dengan baik atau konsisten.",
    "Manusia lebih antusias untuk pindah ke planet lain dengan lingkungan yang tidak bersahabat daripada melestarikan bumi - planet tempat mereka dibentuk dengan sempurna.",
    "Tahap paling bahagia dalam hidup kebanyakan orang adalah ketika otak mereka belum sepenuhnya berkembang.",
    "Jam alarm paling efektif adalah kandung kemih penuh.",
    "Anda mungkin baru saja menyinkronkan kedipan dengan jutaan orang.",
    "Karena kami menguji obat pada hewan terlebih dahulu, obat tikus harus bertahun-tahun di depan pengobatan manusia.",
    "Malam sebelum hari libur lebih memuaskan daripada hari libur yang sebenarnya.",
    "Kami menaruh kertas di folder agar tidak terlipat.",
    "Di suatu tempat, dua sahabat bertemu untuk pertama kalinya.",
    "Otak kita secara bersamaan membenci kita, mencintai kita, tidak peduli dengan kita, dan mengatur setiap gerakan kita.",
    "Menjadi seorang pria adalah masalah kelahiran. Menjadi seorang pria adalah masalah usia. Tapi menjadi seorang pria adalah masalah pilihan.",
    "Segera orang tua akan menyembunyikan akun sosial mereka dari anak-anak mereka daripada anak-anak menyembunyikan akun mereka dari orang tua.",
    "Wikipedia adalah apa yang dimaksud dengan internet.",
    "Sebuah taman hiburan adalah satu-satunya tempat di mana Anda dapat mendengar jeritan di kejauhan dan tidak perlu khawatir.",
    "Pengisi daya telepon nirkabel menawarkan lebih sedikit kebebasan bergerak daripada pengisi daya kabel.",
    "Jika Anda berulang kali mengkritik seseorang karena menyukai sesuatu yang tidak Anda sukai, mereka tidak akan berhenti menyukainya. Mereka akan berhenti menyukai Anda.",
    "Di suatu tempat ada seorang nenek, yang cucunya benar-benar anak laki-laki paling tampan di dunia.",
    "Jika suatu hari nanti teleportasi manusia menjadi nyata, orang masih akan terlambat bekerja.",
    "Manusia pertama yang makan kepiting pasti sangat lapar untuk mencoba dan memakan laba-laba laut lapis baja",
    "Melakukan sesuatu sendirian memang menyedihkan, tapi melakukannya sendiri itu keren.",
    "Otak Anda tiba-tiba menjadi sempurna dalam mengoreksi setelah Anda memposting sesuatu.",
    "Selalu ada satu lagu di daftar putar Anda yang selalu Anda lewati tetapi tidak pernah dihapus.",
    "Anak-anak abad depan mungkin akan membenci kita karena mengambil semua nama pengguna yang bagus.",
    "Gelembung untuk memancing seperti hujan bagi manusia.",
    "Semakin banyak orang yang kamu temui, semakin kamu menyadari dan menghargai seberapa baik orang tuamu membesarkanmu.",
    "Koma adalah jeda singkat, koma adalah jeda panjang.",
    "Suatu hari kamu tidak akan bangun atau tidak tidur.",
    "Segitiga Bermuda mungkin adalah pintu keluar dari simulasi ini.",
    "Jika kita meletakkan panel surya di atas tempat parkir, maka mobil kita tidak akan panas dan kita akan memiliki banyak energi bersih.",
)
